### ISSUE TITLE
Add badges for MIT and ISC License

### ISSUE THREAD

**Issue by vikasganiga05** [forthebadge/for-the-badge#195]
I like to add [MIT](https://choosealicense.com/licenses/mit/) and [ISC](https://choosealicense.com/licenses/isc/) open-source license badge.

#### Badge generator links :point_down: 
- [License MIT](https://forthebadge.com/generator/?plabel=License&slabel=MIT&pbg=%23555555&sbg=%23007EC6)
- [License ISC](https://forthebadge.com/generator/?plabel=License&slabel=ISC&pbg=%23555555&sbg=%23007EC6)

#### Badges will look like this :point_down:
![license-mit](https://user-images.githubusercontent.com/74750414/157791116-416ae36b-56e5-40c4-94e7-8d8a08bf69cf.svg)
![license-isc](https://user-images.githubusercontent.com/74750414/157791111-8c5ad466-eda2-487e-bfdf-501637c9547c.svg)

**Comment by p6afernandes** [comment]
Hey @vikasganiga05 

Thanks for your post and sorry for the delay. My team and I have taken over the project as of September 2023 and all support and upkeep related to this project has been transferred. Check out our new [FAQ ](https://forthebadge.com/#/faq)on the site for more info on this!

In the meantime, Your badges has been added to the site: https://forthebadge.com/images/badges/license-isc.svg & https://forthebadge.com/images/badges/license-mit.svg

Badge on!

**Comment by vikasganiga05** [comment]
> Hey @vikasganiga05
> 
> Thanks for your post and sorry for the delay. My team and I have taken over the project as of September 2023 and all support and upkeep related to this project has been transferred. Check out our new [FAQ ](https://forthebadge.com/#/faq)on the site for more info on this!
> 
> In the meantime, Your badges has been added to the site: https://forthebadge.com/images/badges/license-isc.svg & https://forthebadge.com/images/badges/license-mit.svg
> 
> Badge on!

Thank you for the update, and no worries about the delay. We appreciate your efforts in taking over the project. I've checked out the new FAQ on the site for more details.
