### ISSUE TITLE
Add EICAR Antivirus Test String Badge

### ISSUE THREAD

**Issue by robotfactory** [forthebadge/for-the-badge#231]
I made a badge of the EICAR antivirus test string, used for testing AV software's simple signature based detections. Even in plain text the string is harmless, though it is technically a complete program. You can read more about the test string [here](https://www.eicar.org/download-anti-malware-testfile/)

[https://forthebadge.com/generator/?plabel=X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D&slabel=%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH*](https://forthebadge.com/generator/?plabel=X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D&slabel=%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH*)

![image](https://user-images.githubusercontent.com/354345/195709014-2d84b6ea-c71d-43d9-b911-f45851d62ee0.png)

**Comment by p6afernandes** [comment]
Hey @robotfactory 

Thanks for your PR and sorry for the delay. My team and I have taken over the project as of September 2023 and all support and upkeep related to this project has been transferred. Check out our new [FAQ ](https://forthebadge.com/#/faq)on the site for more info on this!

In the meantime, Your badge has been added to the site: https://forthebadge.com/images/badges/eicar-antivirus-test-string.svg

Badge on!
