### ISSUE TITLE
3+ panel badge?

### ISSUE THREAD

**Issue by ajlowndes** [forthebadge/for-the-badge#249]
Did a bit of searching online, couldn't find any instance where a 3+ panel badge was made/used. I have one I want to make, it would look like this:

ON BELAY CLIMB WHEN READY | CLIMBING | CLIMB ON

I imagine the last panel would be the same style as the first, because the badge represents a common conversation between rock-climbing partners.

Any idea how I could do this, even outside of forthebadge?

**Comment by p6afernandes** [comment]
Hey @ajlowndes 

Thanks for your post and sorry for the delay. My team and I have taken over the project as of September 2023 and all support and upkeep related to this project has been transferred. Check out our new [FAQ ](https://forthebadge.com/#/faq)on the site for more info on this!

I just coded and pushed this feature into production as apart of our generator, take a look here: https://forthebadge.com?primaryBGColor=%2331C4F3&primaryTextColor=%23FFFFFF&secondaryBGColor=%23389AD5&secondaryTextColor=%23FFFFFF&tertiaryBGColor=%2331c4f3&tertiaryTextColor=%23FFFFFF&primaryLabel=ON+BELAY+CLIMB+WHEN+READY&secondaryLabel=CLIMBING&tertiaryLabel=CLIMB+ON&panels=3#/generator

Badge on!
